project:
  type: website

website:
  google-analytics: G-6L9XKPY52W
  site-url: https://strategic-consult.com
  announcement:
    icon: info-circle
    dismissable: true
    content: "IMMR-6 Coming Soon in 2025. Contact us for more details."
    position: below-navbar
  page-footer: © Copyright 2025 Strategic Consulting, Inc.
  favicon: assets/favicon.png
  title: "Strategic Consulting"
  search:
    location: navbar
    type: textbox
  navbar:
    left:
      - text: About SCI
        menu:
          - href: about.qmd
            text: About Strategic Consulting, Inc.
          - href: management.qmd
            text: Management
          - href: clients.qmd
            text: Our Clients
      - text: Market Reports
        menu:
          - href: market-reports.qmd
            text: Market Reports Overview
          - href: immr5.qmd
            text: Industrial Microbiology Market, 5th Ed.
      - text: Consulting Services
        href: services.qmd
      - href: news.qmd
        text: News
      - href: contact.qmd
        text: Contact
    right:
      - icon: linkedin
        href: "https://www.linkedin.com/in/bobferguson9806/"
  sidebar:
    logo: assets/strategic-logo.png
    logo-alt: "The Strategic Consulting Inc. Logo"

format:
  html:
    include-in-header:
      - text: |
          <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+2A41PpI1ytTtF0UbGp3FScKbsyI7" crossorigin="anonymous"></script>
      - text: |
          <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFM77uVsg9s9H24iwvdIh5sRLq7nhu0BtI7ef" crossorigin="anonymous">
    theme: lux
    css: styles.css
    toc: true









