---
title: "About"
---

# About Strategic Consulting Inc.

Founded in 1996, Strategic Consulting, Inc. (SCI) is the leading knowledge resource for business strategy and market intelligence in the industrial microbiology diagnostics industry.

Strategic Consulting’s focus is microbiology-based, quality and safety testing for the food, beverage, pharmaceutical, and personal care product industries, and for environmental and industrial process water. SCI also works with companies offering technologies and products in the human/clinical, veterinary, and agricultural markets.

Strategic Consulting’s long tenure in the industrial diagnostics industry includes the publication of 20 market research reports addressing critical market topics over the last 28 years. Strategic Consulting market research reports are widely accepted by leading diagnostic manufacturers and investors as highly credible analyses of the industry.

SCI’s business consulting services focus on strategy development, management and tactical implementation, business development, and market research.

Strategic Consulting’s consultants are located around the world and are experienced executives from the industrial marketplace, with proven successes with venture capital backed start-ups, publicly traded companies, transformation of underachieving companies, and technology acquisitions.

Together they deliver actionable recommendations for improving client company performance backed by years of pragmatic, real-world experience.
