# Our Clients

Strategic Consulting clients are focused in the food, beverage, environmental, pharmaceutical and personal care/cosmetics segments of the industrial market, including diagnostic companies, laboratories and the investors (PE/VC) in these markets. We work with venture capital backed start-ups, publicly traded companies, technology acquisitions, and transformation of underachieving companies.

Our market research reports are widely accepted by leading diagnostic manufacturers and investors as highly credible analyses of the industry and are often cited in publications and M&A offer memorandums.  As a result, top-tier, market-leading industrial diagnostic companies are repeat customers who have purchased hundreds of our reports. Our clients also draw on our many years of experience in the industrial marketplace through our custom consulting services, which include strategy development, management and tactical implementation, business development, sales strategy,  global expansion and market research.

Strategic Consulting has also been involved offering buy-side consulting in the major and prominent M&A activity and financing deals in the Industrial Microbiology market over the past two decades.

Strategic Consulting’s Clients include the following companies:

- 3M
- Bain Capital
- Battery Ventures
- BD
- Berkshire Partners
- Biolog
- bioMerieux
- Bio-Rad
- Blackstone Group
- Boston Consulting Group
- Charles River Laboratory
- Chemunex
- CHROMagar
- Clear Labs
- Continental Grain
- Corning
- Cytiva
- Danaher
- Ecolab
- EnviroLogix
- Ernst & Young
- Eurofins
- Fortive
- FOSS
- Fisher Scientific
- GE Healthcare
- Golden Gate Capital
- Hach
- Hardy Diagnostics
- Hygiena
- IDEXX
- IGS Boston
- Illumnia
- Innovative Biosensors
- Kikkoman
- LabCorp
- LuminUltra
- Maxim Integrated Products
- Merck Sigma
- Morgan Stanley
- Neogen
- Novolyze
- Pall Corporation
- Paradigm Diagnostics
- Particle Monitoring Systems
- PerkinElmer
- Purdue University
- QIAGEN
- QualiTru
- r-biopharm
- Riverside Capital
- Singulex
- Taylor Companies
- Testo & Co.
- ThermoFisher
- University of Cincinnati
- Upland Nanotech
- Waters
- Whirl-Pak