# Industrial Microbiology Market Review, Fifth Edition: Global Review of Microbiology Testing in the Industrial Market

(*IMMR-5*)

Industrial Microbiology Market Review, Fifth Edition: Global Review of Microbiology Testing in the Industrial Market (*IMMR—5*) is a new, extensively researched analysis of the sizable market for microbiological testing in the industrial market. *IMMR—5* tracks and compares microbiology test volumes, market values and methods used by companies in the production of safe and wholesome products that meet label claims.

*IMMR—5* includes global test volumes and growth in industrial microbiology with further analysis of market sectors, geographic regions, test methods, organisms tested and sample sources. Current market values are detailed as well as projected market estimates, including 5-year projections of both testing volumes and market value, *IMMR—5* provides critical input to strategic planning.

Strategic Consulting collected data from more than 850 companies and processor locations in 70 countries around the world as input to *IMMR—5*. *IMMR—5* includes data from the fast-growing countries and markets throughout Asia and Latin America and includes a separate review of the Food and Pharma market in China and the Food market in Brazil.

*IMMR—5* is based on primary research with the key quality assurance managers and other knowledgeable individuals at production facilities in all six sectors of the industrial microbiology market:

- Food
- Beverage
- Pharmaceuticals
- Personal Care Products and Cosmetics
- Environmental Water
- Industrial Processes

Analysis of each market sector includes testing by organism and methods used worldwide and in geographic regions (North America, Europe, Asia and ROW-Rest of the World) as well as a discussion of regulatory and topical issues specific to each sector.

*IMMR—5* also includes a thorough discussion of market trends and drivers; a business review of the industrial diagnostics market including competition, consolidation and key success factors; and detailed company profiles of 21 of the leading companies serving the industrial diagnostics market including 17 leading test manufacturers and 4 major laboratory companies, with laboratories profiled for the first time due to the changing dynamics of the market and the greater influence they are having in industrial diagnostics.

## Request Prospectus

<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSfhuO3Wxvnv3rJF5_wsdHRtH6vYoT7KK9ypugeoS5ILL5Lj7Q/viewform?embedded=true" width="640" height="1093" frameborder="0" marginheight="0" marginwidth="0">Loading…</iframe>