# Welcome to Strategic Consulting, Inc.

## Industrial Diagnostics, Market Research, Marketing Communications, and Business Strategy

Strategic Consulting is the leading knowledge resource for business strategy and market intelligence in industrial diagnostics. We focus on microbiology-based, quality/safety testing for the food, beverage, pharmaceutical, and personal care product industries, and for environmental water and industrial processes.

Our extensive industry knowledge and insights are built on more than 100 years of combined experience in the field, and strengthened by ongoing primary research and interviews with key industrial diagnostics customers and competitors.

In his 30-year career in industrial and molecular diagnostics, SCI President Thomas R. Weschler, has created and executed on a range of businesses including venture capital backed start-ups, publicly traded companies and new technology acquisitions.

With more than 30 years in industrial and environmental diagnostics and laboratory businesses, SCI Managing Director Robert J. Ferguson has demonstrated success in accelerating growth, international business development, sales force implementation and improvement, business turnarounds, M&A, and new product development in businesses ranging from start-ups to Fortune 500 corporations.

SCI’s list of more than 160 clients includes major industrial diagnostic companies as well as new entrants and investors. Strategic Consulting market research reports and business consulting services deliver sound market analyses and strategies for profitability and success.

## Expert Consulting
Our pragmatic, action-oriented approach to corporate strategy, business development and marketing communications is built on a critical understanding of the industrial diagnostics marketplace, technologies, and competitors. [Read More...](services.qmd)

## Market Reports
Our food, pharmaceutical and industrial microbiology market research reports are based on extensive primary research, and widely accepted by leading diagnostic manufacturers and investors as highly credible analyses of the industry. [Read More...](market-reports.qmd)
