# Market Reports Overview
Strategic Consulting’s long tenure in industrial diagnostics includes the publication of more than 20 comprehensive market reports over the last 28 years. Top-tier competitors within industrial diagnostics have purchased hundreds of our reports.

> "Thank you so much for the market reports.  I have to say, amongst everything I have read on this space, these are the most impressive and accurate reports I’ve seen. Actually, they’re probably the best reports I’ve read in any market…"

> Molecular Diagnostics Company CEO

Every SCI market report is based on our extensive primary research with:

- Production facilities
- Senior quality/safety officers in the leading companies
- Key opinion leaders
- Regulatory experts
- Diagnostic companies participating in the field.

SCI market research reports include analyses of current and emerging trends, market-size projections and a thorough review of competitors.

Written in an easy-to-read style with clear data and graphs, Strategic Consulting market reports are designed to help you make sound business decisions.
<br>

## Now available
### INDUSTRIAL MICROBIOLOGY MARKET REVIEW, SIXTH EDITION: GLOBAL REVIEW OF MICROBIOLOGY TESTING IN THE INDUSTRIAL MARKET: 2025 - 2029 {#immr6}
We are pleased to announce that the **Industrial Microbiology Markets Report, 6th Edition (IMMR-6)** is now published and available.

The Industrial Microbiology Segment is a dynamic market currently consisting of more than three billion tests with a global market value of > $13 billion and forecast to grow between 6% - 8% through 2029.

The IMMR-6 report covers the Industrial Microbiology Markets in Six major segments including;

- Food
- Beverages
- Pharmaceuticals
- Personal Care / Cosmetics
- Water/Wastewater
- Industrial Processes

This new IMMR-6 report – like all Strategic Consulting reports - is based on primary data collected from >1,000 companies in 60 countries plus additional data collected through thousands of interviews and surveys with end-users at food processors, laboratories, manufacturers of test kits/instruments and other companies in the market.

Please [contact us](contact.qmd) for more details or download the <a download href="assets\IMMR-6 Report Prospectus July 2025.pdf">report prospectus</a> here.

<br>

## Industrial Microbiology Market Review, Fifth Edition: Global Review of Microbiology Testing in the Industrial Market
*Industrial Microbiology Market Review, Fifth Edition: Global Review of Microbiology Testing in the Industrial Market (IMMR—5)* is a new, extensively researched analysis of the sizable market for microbiological testing in the industrial market. IMMR—5 tracks and compares microbiology test volumes, market values and methods used by companies in the production of safe and wholesome products that meet label claims.

[Read More...](immr5.qmd)