# Our Consulting Services
Strategic Consulting actively helps clients develop and implement winning strategies for industrial diagnostic markets. We recommend pragmatic strategies that can be reasonably achieved, believing that accurate planning succeeds only when it can be efficiently executed.

With more than 100 combined years in industrial diagnostics, our consultants have walked in your shoes, faced the same challenges and been successful. We possess extensive industry knowledge and seasoned expertise in a range of industrial diagnostics markets including beverage and food safety testing, pharmaceutical rapid microbiology, and molecular diagnostics for environmental and industrial process water.
SCI can lead or support your company in the business-critical, strategic planning process. We help integrate customer feedback, assess market potential, determine competitor strengths/weaknesses, review technology/product potential, and integrate market trends/threats into a pragmatic and winning plan.


## Business Management and Tactical Implementation {.unnumbered .unlisted}
```{=html}
<button class="btn btn-outline-primary collapsed"  type="submit" data-bs-toggle="collapse" data-bs-target="#collapse1" aria-expanded="false" aria-controls="collapse1">
    Read More...
</button>
```
:::: {#collapse1 .collapse}
::: {.card .card-body .bg-light}
SCI actively supports the execution of your strategic and tactical plans. We mentor management teams, facilitate product development and launch, design and facilitate sales training and establish or expand domestic/international distribution channels. We mediate product/technology licensing, partnering or private-labeling, and develop and recruit marketing/sales organizations.
:::
:::

---

## Business Development {.unnumbered .unlisted}
```{=html}
<button class="btn btn-outline-primary collapsed"  type="submit" data-bs-toggle="collapse" data-bs-target="#collapse2" aria-expanded="false" aria-controls="collapse2">
    Read More...
</button>
```
:::: {#collapse2 .collapse}
::: {.card .card-body .bg-light}
SCI supports the implementation of your strategic business plan through sourcing of equity financing, acquisition/divestiture of technologies, products or companies, and the establishment of strategic partnerships. SCI has worked with many established and start-up companies on their strategy, development and exit-strategies. SCI has also worked with several university biotech incubators in finding opportunities for their promising technologies and developing and executing on exit strategies.

### Incubator Start-up {.unnumbered .unlisted}
A start-up food safety diagnostic company in a university incubator wanted to effectively develop their business model and an exit strategy. We assessed optimum market niches where they would have competitive advantages, developed their sales team to find and close sales opportunities driving revenue assisted in the technical product development to better meet customer needs and ultimately facilitated contacts with acquisition partners resulting in successful sale and exit from the incubator to a profitable division of a successful diagnostic company.
:::
:::

---

## Global Expansion {.unnumbered .unlisted}
```{=html}
<button class="btn btn-outline-primary collapsed"  type="submit" data-bs-toggle="collapse" data-bs-target="#collapse3" aria-expanded="false" aria-controls="collapse3">
    Read More...
</button>
```
:::: {#collapse3 .collapse}
::: {.card .card-body .bg-light}
SCI has the experience and geographical positioning to help your company successfully expand distribution beyond your home territories or broaden its coverage around the world.

### Global Distribution {.unnumbered .unlisted}
A major international industrial company with a diagnostic testing division wanted to expand its global footprint and expand its market access and distribution network around the world.  We assessed market and product opportunities,  competitive dynamics in each regional market and identified, evaluated potential distribution partners and represented the company in negotiations of distribution agreements acheiving the company's goal of global distribution.
:::
:::

---

## Custom Market Research {.unnumbered .unlisted}
```{=html}
<button class="btn btn-outline-primary collapsed"  type="submit" data-bs-toggle="collapse" data-bs-target="#collapse4" aria-expanded="false" aria-controls="collapse4">
    Read More...
</button>
```
:::: {#collapse4 .collapse}
::: {.card .card-body .bg-light}
SCI provides thorough industry analyses through custom primary market research that includes research design, survey development and execution, customer profiling, market needs analysis, customer and competitor profiling, and commercial-potential determinations.  SCI conducts 100s of independent market and customer surveys annually.  We understand the “Voice of the Customer” first-hand, through our work with the people who use and buy microbiological tests technologies.

### Global Market Evaluation {.unnumbered .unlisted}
A major international diagnostic industrial company with substantial diagnostic test offerings needed a complete evaluation of their international business across six world regions and a better understanding of their market share, market growth rates and market opportunities, both organic and inorganic..  Strategic Consulting developed a complete evaluation of their total market position including their total and accessible market size by product line and region, their strengths and weaknesses globally and by region and by product line.  The company found that the depth and scope of this evaluation produced more actionable insights into their opportunities in the industrial microbiology marketplace than would have been possible working with a conventional business consulting firm.

### Market Research and Assessment
A private European diagnostic company was evaluating opportunities for its technology in a new market segment. Strategic Consulting conducted market research with end customers to detail their current testing practices and evaluate receptiveness to our client’s new technology. In addition, overall market size was determined and the client’s potential competitive share and penetration projected.
:::
:::

---

## Business Strategy and Development {.unnumbered .unlisted}
```{=html}
<button class="btn btn-outline-primary collapsed"  type="submit" data-bs-toggle="collapse" data-bs-target="#collapse5" aria-expanded="false" aria-controls="collapse5">
    Read More...
</button>
```
:::: {#collapse5 .collapse}
::: {.card .card-body .bg-light}
### Business Line Expansion {.unnumbered .unlisted}
A mid-size diagnostic company with a very successful niche diagnostic technology was finding it difficult to discover new growth opportunities. We helped them evaluate the diagnostic market and identify technical market adjacencies as well as inorganic opportunities for adding complimentary technologies. We were able to identify and helped them close on an acquisition that resulted in tangible sales growth in the food safety and clinical markets, significantly accelerated their overall business growth.

### International Development {.unnumbered .unlisted}
A major international diagnostic company wanted to expand their knowledge of the diagnostic markets in Asia and discover and understand the best points of entry in those multiple markets.  We started with a customer market evaluation of the markets in China, South Korea, Taiwan, Vietnam, India, and Thailand.  The project involved details characterization of the markets and their growth rates and product use.  The work also involved Voice of Customer interviews conducted in multiple languages and assessment of the best products and services to meet the client’s needs.
:::
:::

---

## Mergers, Acquisitions, and Buy-Side Consulting {.unnumbered .unlisted}
```{=html}
<button class="btn btn-outline-primary collapsed"  type="submit" data-bs-toggle="collapse" data-bs-target="#collapse6" aria-expanded="false" aria-controls="collapse6">
    Read More...
</button>
```
:::: {#collapse6 .collapse}
::: {.card .card-body .bg-light}
### Buy-Side Consulting {.unnumbered .unlisted}
A major industrial with a diagnostic arm has relied on Strategic Consulting for buy-side consulting for multiple projects from several related to food safety diagnostics and equipment, laboratory services and equipment, evaluation of diagnostic software companies, food sanitation and disinfectant chemical companies and major acquisition opportunities in auction/carve-out situations.  Strategic Consulting has played a key role in their understanding of the market opportunities and risks, competition, growth rates, and customer attitudes toward the acquisition targets.

### Buy-Side Consulting {.unnumbered .unlisted}
Strategic Consulting worked with one of the largest Wall Street private equity firms on one of the largest acquisitions in the industrial diagnostics space in recent years.  We conducted a thorough risk and opportunity analysis, growth rate forecasting and evaluation of post-acquisition organic and inorganic growth opportunities, resulting in a successfully multi-billion dollar acquisition.

:::
:::

---


