# Who We Work With
Strategic Consulting clients are diagnostic companies focused in the food, beverage, environmental and pharmaceutical segments of the industrial market. We also work with companies that offer technologies and products in the human/clinical, veterinary, and agricultural markets. Our 160+ clients include major companies in the industrial diagnostics industry as well as new entrants and financial institutions. We work with venture capital backed start-ups, publicly traded companies, technology acquisitions, and transformation of underachieving companies.

---

<strong>A leading instrument company</strong> was considering entry into food diagnostics with its new technology.

```{=html}
<button class="btn btn-outline-primary collapsed"  type="submit" data-bs-toggle="collapse" data-bs-target="#collapse1" aria-expanded="false" aria-controls="collapse1">
    Read More...
</button>
```
:::: {#collapse1 .collapse}
::: {.card .card-body .bg-light}
### Business Strategy {.unnumbered .unlisted}
A leading instrument company was considering entry into food diagnostics with its new technology. Strategic Consulting mentored the project team as it evaluated new product opportunities. We also assisted with market research, market potential assessment and a business model that generated a go/no-go recommendation for the company president.
:::
:::

---

<strong>A private European diagnostic company</strong> was evaluating opportunities for its technology in a new market segment.

```{=html}
<button class="btn btn-outline-primary collapsed"  type="submit" data-bs-toggle="collapse" data-bs-target="#collapse2" aria-expanded="false" aria-controls="collapse2">
    Read More...
</button>
```
:::: {#collapse2 .collapse}
::: {.card .card-body .bg-light}
### Market Research and Assessment {.unnumbered .unlisted}
A private European diagnostic company was evaluating opportunities for its technology in a new market segment. Strategic Consulting conducted market research with end customers to detail their current testing practices and evaluate receptiveness to our client’s new technology. In addition, overall market size was determined and the client’s potential competitive share and penetration projected.
:::
:::

---

<strong>A supplier of laboratory and industrial FDA-grade disposable plastics</strong> sought a more productive distribution strategy to improve low market penetration and gross margins in Europe.

```{=html}
<button class="btn btn-outline-primary collapsed"  type="submit" data-bs-toggle="collapse" data-bs-target="#collapse3" aria-expanded="false" aria-controls="collapse3">
    Read More...
</button>
```
:::: {#collapse3 .collapse}
::: {.card .card-body .bg-light}
### International Stratregy Formulation and Implementation {.unnumbered .unlisted}
A supplier of laboratory and industrial FDA-grade disposable plastics sought a more productive distribution strategy to improve low market penetration and gross margins in Europe. Strategic Consulting recommended they change from using distributors in that market to direct sales with a streamlined supply chain. Now in progress, this medium-to-long term plan will move to European manufacturing to take advantage of government subsidies and financial support.
:::
:::

---

<strong>A Scandinavian start-up company</strong> had novel technology and the desire to enter the industrial diagnostics market.

```{=html}
<button class="btn btn-outline-primary collapsed"  type="submit" data-bs-toggle="collapse" data-bs-target="#collapse4" aria-expanded="false" aria-controls="collapse4">
    Read More...
</button>
```
:::: {#collapse4 .collapse}
::: {.card .card-body .bg-light}
### Business Management {.unnumbered .unlisted}
A Scandinavian start-up company had novel technology and the desire to enter the industrial diagnostics market. Strategic Consulting guided the company through development of its initial business plan, two rounds of equity financing, launch of its commercial products, and establishment of strategic distribution partnerships.
:::
:::

---

<strong>A life science diagnostics company</strong> wanted to enter the industrial diagnostic market.

```{=html}
<button class="btn btn-outline-primary collapsed"  type="submit" data-bs-toggle="collapse" data-bs-target="#collapse5" aria-expanded="false" aria-controls="collapse5">
    Read More...
</button>
```
:::: {#collapse5 .collapse}
::: {.card .card-body .bg-light}
### Management Mentoring and Recruitment {.unnumbered .unlisted}
A life science diagnostics company wanted to enter the industrial diagnostic market. We assisted in their business planning process, mentored senior management, and provided key personnel recruiting services to aid in the establishment of a new division dedicated to industrial markets.
:::
:::

---

<strong>A food, biochemical, and diagnostics company in Japan</strong> planned to launch its product/technology in the US.

```{=html}
<button class="btn btn-outline-primary collapsed"  type="submit" data-bs-toggle="collapse" data-bs-target="#collapse6" aria-expanded="false" aria-controls="collapse6">
    Read More...
</button>
```
:::: {#collapse6 .collapse}
::: {.card .card-body .bg-light}
### Market Assessment {.unnumbered .unlisted}
A food, biochemical and diagnostics company in Japan planned to launch its product/technology in the US. We assessed market and product opportunities, and reviewed competitive products and technologies. Strategic Consulting also identified and evaluated possible strategic partners to aid in US business development.
:::
:::

---

<strong>A leading diagnostic company</strong> sought increased market penetration for its products/technology.

```{=html}
<button class="btn btn-outline-primary collapsed"  type="submit" data-bs-toggle="collapse" data-bs-target="#collapse7" aria-expanded="false" aria-controls="collapse7">
    Read More...
</button>
```
:::: {#collapse7 .collapse}
::: {.card .card-body .bg-light}
### Customer Satisfaction and Strategy Assessment {.unnumbered .unlisted}
A leading diagnostic company sought increased market penetration for its products/technology. Strategic Consulting interviewed existing customers to assess their satisfaction. In addition, interviews were conducted with prospective customers who had decided to use competitors’ products. Based on these inputs, we recommended changes in strategy for distribution, R&D, and marketing plans.
:::
:::

---

<strong>A microbiological media company</strong> wanted to expand distribution channels in its existing markets and develop strategic partners in new markets for its proprietary packaging technology.

```{=html}
<button class="btn btn-outline-primary collapsed"  type="submit" data-bs-toggle="collapse" data-bs-target="#collapse8" aria-expanded="false" aria-controls="collapse8">
    Read More...
</button>
```
:::: {#collapse8 .collapse}
::: {.card .card-body .bg-light}
### Strategic Planning and Business Development {.unnumbered .unlisted}
A microbiological media company wanted to expand distribution channels in its existing markets and develop strategic partners in new markets for its proprietary packaging technology. Strategic Consulting provided sales/marketing management and developed a strategic plan. We then identified and negotiated strategic partner licensing and OEM/private-labeling in the US and distribution agreements in South Africa, Korea, Europe, and Japan.
:::
:::

